### ISSUE TITLE
Won't let me exit back to LiveArea

### ISSUE THREAD

**Issue by AcidicPeridot** [Ibrahim778/BetterHomebrewBrowser#22]
I cant press the home button and im forced to shut down my vita to close down the app.

**Comment by Ibrahim778** [comment]
Due to the nature of the app, any hangup inside will freeze the entire vita because it runs on the fourth core
Please be a bit more descriptive with what exactly the app was doing which caused said issue and any other helpful information you may be able to provide, also please ensure you're using the latest version.

**Comment by BoxWithAHat** [comment]
I have this issue as well. The app is not crashed, however attempting to press the home button in any screen of the app will cause the "no" (🚫) symbol to appear in the top left corner of the screen.

**Comment by MollyRaw** [comment]
> 

Same issue, there’s no work around. So much for the ‘Better’ HBB lmao. It also freezes a lot.

**Comment by Ibrahim778** [comment]
Calm down, I've been busy with school lately. Can you explain what it was that you were doing before this happened, and what the app showed on screen?
I would fix this small bug if I could. But there have been updates to the paf headers and I've completely moved my dev environment since the last release so it'd be too time consuming to try and get the source code for that last release to build.
The only reason I have found this to be happening is if a data file download fails to start within the app, a bug I have patched since then. You'll have to wait for the new version, but again, I'm busy with school so it might take a bit

**Comment by MollyRaw** [comment]
No worries man it’s not a big issue we don’t blame you

**Comment by prodko** [comment]
Hello! Just to provide a quick update for the dev on this issue, on a fresh install of bhbb for me at least when i open an apps page everything works normal when i hit the download button it loads for a moment then it says that the download has been added to the live area. it is at this point that we are no longer able to exit back to the livearea as it gives us the "no" (🚫) symbol in the top left hand corner. this happens with both sources as well and restarting the vita does not provide us with a finished download. however if we were to repeat the process and then hit refresh in the settings the app will crash. this error also occurs whether it be right when you turn on the vita or after you have opened a few apps. additionally there is no pop up showing that the download has started in the live area. only the in app notification for it appears. i think thats as much information i can give besides im running cfw on 3.65.

**Comment by dayve218** [comment]
i also have the same issue as described by @prodko

**Comment by Soundtoxin** [comment]
I just hit this same issue. I took a screenshot or two (it stopped letting me take them pretty quick), searched and browsed a few things. Tried to download EasyRPG Player but it said it couldn't find a source or something. Also this was my initial launch so I was downloading the icons this whole time.

Thanks @prodko for the tip of refreshing a bunch to make it crash. That was able to get me out of it without restarting my Vita. It's pretty scary that an app can just trap you like that. I wish there were some sort of ultimate back/kill/override I could use in these situations.

**Comment by Ibrahim778** [comment]
I've made a lot of progress so expect a release soon.
For your ultimate back/kill/override, I can suggest installing my quicklaunch plugin from [here](https://github.com/Ibrahim778/QuickLauncher). 
That way you have shortcuts to open other apps in the quick menu, so next time you're stuck just open quick menu and open any app and it'll kick you out of BHBB.

**Comment by Ibrahim778** [comment]
A new version has been released, this issue should be fixed. Feel free to re-open if it isn't.
